name: Build and Release Python App

on:
  push:
    branches:
      - 'main'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.9'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pyinstaller

    - name: Build binary
      run: pyinstaller --onefile setup.py

    - name: Archive binary
      run: zip -j setup.zip dist/setup

    - name: Get commit hash
      id: get_commit_hash
      run: echo ::set-output name=COMMIT_HASH::$(git rev-parse --short HEAD)

    - name: Create Release
      id: create_release
      uses: actions/create-release@v1
      env:
        GITHUB_TOKEN: ${{ secrets.MY_GITHUB_TOKEN }}
      with:
        tag_name: ${{ steps.get_commit_hash.outputs.COMMIT_HASH }}
        release_name: Release ${{ steps.get_commit_hash.outputs.COMMIT_HASH }}
        draft: false
        prerelease: false
        body: |
          ## Changes
          - Your changelog here

    - name: Upload Release Asset
      uses: actions/upload-release-asset@v1
      with:
        upload_url: ${{ steps.create_release.outputs.upload_url }}
        asset_path: ./setup.zip
        asset_name: setup.zip
        asset_content_type: application/zip
